name: step-build
on:
  workflow_dispatch:
    ## o mais proximo dos parametros do azuredevops 
    inputs:
      environment:
        type: choice
        description: environment
        options:
        - dev
        - hml
        - prd

jobs: 
  call-workflow:
    secrets: inherit            
    uses: Buzinho2022/build-templates/.github/workflows/worker-csharp.yml@main
    with:                       
      solution: ${{ github.event.inputs.solution }}
      environment: ${{ github.event.inputs.environment }}
      namespace: ${{ github.event.inputs.namespace }}
